const ERROR = {
    NONE: 'NONE',
    USERNAME_IN_USE: 'USERNAME_ALREADY_IN_USE',
    EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
    ALREADY_CONTACT: 'ALREADY_MADE_CONTACT',
    ALREADY_SEND_REQUEST: 'ALREADY_SEND_REQUEST',
}

export default ERROR;